# Part 1

# Sonoff RF Bridge / eWeLink application
sonoff:
  username: your@email.com
  password: your eWeLink password
  reload: always # update device list every time HA starts


# Part 2 (add the new stuff only):

# Sonoff RF Bridge / eWeLink application
sonoff:
  username: your@email.com
  password: your eWeLink password
  reload: always # update device list every time HA starts
  rfbridge:
    Motion 1:  # sensor name in eWeLink application
      device_class: motion
      timeout: 60  # optional (default 120), timeout in seconds for auto turn off
